In [20]:
import numpy as np
import pandas as pd
import torch
import torch.utils.data as Data

In [314]:
source_x = pd.read_csv(r'D:/个人资料/研究生/机器学习/Jupyter/迁移学习练习赛-2/run/data/source_x.csv').iloc[:,1:]
source_y = pd.read_csv(r'D:/个人资料/研究生/机器学习/Jupyter/迁移学习练习赛-2/run/data/source_y.csv').iloc[:,1:]
target_x = pd.read_csv(r'D:/个人资料/研究生/机器学习/Jupyter/迁移学习练习赛-2/run/data/target_x.csv').iloc[:,1:]
target_y = pd.read_csv(r'D:/个人资料/研究生/机器学习/Jupyter/迁移学习练习赛-2/run/data/target_y.csv').iloc[:,1:]
# test = pd.read_csv(r'data/test.csv')

In [315]:
source_x.head()

Cylinders  Displacement  Horsepower    Weight  Acceleration  Model Year  \
0  -0.869348     -1.009459   -0.784052 -1.025303     -0.379759   -0.516397   
1  -0.869348     -0.530218   -0.442811 -0.118796      0.624102    0.843910   
2   1.483887      1.482595    1.447140  1.736877     -0.738281   -1.060519   
3  -0.869348     -0.865687   -1.099044 -1.025303     -0.308055    1.660094   
4  -0.869348     -0.942365   -0.994047 -1.001603      0.875068    1.115971   

        USA    Europe     Japan  
0  0.774676 -0.465148 -0.495225  
1  0.774676 -0.465148 -0.495225  
2  0.774676 -0.465148 -0.495225  
3  0.774676 -0.465148 -0.495225  
4 -1.286751 -0.465148  2.012852

In [205]:
source_x = source_x.astype('float32')

In [206]:
source_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314 entries, 0 to 313
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Cylinders     314 non-null    float32
 1   Displacement  314 non-null    float32
 2   Horsepower    314 non-null    float32
 3   Weight        314 non-null    float32
 4   Acceleration  314 non-null    float32
 5   Model Year    314 non-null    float32
 6   USA           314 non-null    float32
 7   Europe        314 non-null    float32
 8   Japan         314 non-null    float32
dtypes: float32(9)
memory usage: 11.2 KB


In [196]:
for i in [source_x,target_x]:
    for j in ['Cylinders', 'Displacement', 'Horsepower', 'Weight',
       'Acceleration', 'Model Year', 'USA', 'Europe', 'Japan']:
#     print(i.columns)
        i[j] = i[j].astype('float32')
#     i = pd.DataFrame(i,dtype=np.float32)
for i in [source_y,target_y]:
    i['MPG'] = i['MPG'].astype('float32')
#     print(i.columns)

In [104]:
source_x = source_x.iloc[:,1:]
source_x.head()

Cylinders  Displacement  Horsepower    Weight  Acceleration  Model Year  \
0  -0.869348     -1.009459   -0.784052 -1.025303     -0.379759   -0.516397   
1  -0.869348     -0.530218   -0.442811 -0.118796      0.624102    0.843910   
2   1.483887      1.482595    1.447140  1.736877     -0.738281   -1.060519   
3  -0.869348     -0.865687   -1.099044 -1.025303     -0.308055    1.660094   
4  -0.869348     -0.942365   -0.994047 -1.001603      0.875068    1.115971   

        USA    Europe     Japan  
0  0.774676 -0.465148 -0.495225  
1  0.774676 -0.465148 -0.495225  
2  0.774676 -0.465148 -0.495225  
3  0.774676 -0.465148 -0.495225  
4 -1.286751 -0.465148  2.012852

In [306]:
source_x = torch.from_numpy(np.array(
    (pd.read_csv(r'D:/个人资料/研究生/机器学习/Jupyter/迁移学习练习赛-2/run/data/source_x.csv').iloc[:,1:]).astype('float32')))
source_y = torch.from_numpy(np.array(
    (pd.read_csv(r'D:/个人资料/研究生/机器学习/Jupyter/迁移学习练习赛-2/run/data/source_y.csv').iloc[:,1:]).astype('float32')))
target_x = torch.from_numpy(np.array(
    (pd.read_csv(r'D:/个人资料/研究生/机器学习/Jupyter/迁移学习练习赛-2/run/data/target_x.csv').iloc[:,1:]).astype('float32')))
target_y = torch.from_numpy(np.array(
    (pd.read_csv(r'D:/个人资料/研究生/机器学习/Jupyter/迁移学习练习赛-2/run/data/target_y.csv').iloc[:,1:]).astype('float32')))

In [307]:
source_x.dtype

torch.float32

In [308]:
# source_x = torch.unsqueeze(source_x,1)
source_x = torch.unsqueeze(source_x,1)
# target_x = torch.unsqueeze(target_x,1)
target_x = torch.unsqueeze(target_x,1)

In [309]:
source_y = torch.squeeze(source_y,1)
target_y = torch.squeeze(target_y,1)

In [310]:
source_data = Data.TensorDataset(source_x, source_y)
target_data = Data.TensorDataset(target_x, target_y)

In [311]:
source_data = Data.DataLoader(dataset=source_data,batch_size=50,shuffle=True)
target_data = Data.DataLoader(dataset=target_data,batch_size=50,shuffle=True)

In [312]:
for step, (x,y) in enumerate(target_data):
    print('第{}个样本的图片大小为{}，标签大小为{}'.format(step + 1, x.shape, y.shape))
    print(x.dtype)
    print(y.shape)
    if step == 1:
        break

第1个样本的图片大小为torch.Size([50, 1, 9])，标签大小为torch.Size([50])
torch.float32
torch.Size([50])
第2个样本的图片大小为torch.Size([28, 1, 9])，标签大小为torch.Size([28])
torch.float32
torch.Size([28])


In [33]:
source_x

tensor([[146.0000,  -0.8693,  -1.0095,  ...,   0.7747,  -0.4651,  -0.4952],
        [282.0000,  -0.8693,  -0.5302,  ...,   0.7747,  -0.4651,  -0.4952],
        [ 69.0000,   1.4839,   1.4826,  ...,   0.7747,  -0.4651,  -0.4952],
        ...,
        [150.0000,  -0.8693,  -0.8369,  ...,  -1.2868,  -0.4651,   2.0129],
        [145.0000,  -0.8693,  -1.0766,  ...,  -1.2868,  -0.4651,   2.0129],
        [182.0000,  -0.8693,  -0.8465,  ...,  -1.2868,   2.1430,  -0.4952]],
       dtype=torch.float64)

In [10]:
a = torch.ones(2,2)
b = a.numpy()

In [12]:
a

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
source_data = Data.TensorDataset(source_x, source_y)
target_data = Data.TensorDataset(target_x,target_y)

In [52]:
import torch
from torchvision import datasets, transforms

import params

#
import pandas as pd
import numpy as np

In [228]:
def get_mnist(train=True):
    """Get MNIST dataset loader."""
    # image pre-processing图像预处理
    pre_process = transforms.Compose([transforms.ToTensor(),
                                      transforms.Normalize([0.5], [0.5])])
#                                       transforms.Normalize(
#                                           mean=params.dataset_mean,
#                                           std=params.dataset_std)])

    # dataset and data loader
    mnist_dataset = datasets.MNIST(root=params.data_root,
                                   train=train,
                                   transform=pre_process,
                                   download=False)

    mnist_data_loader = torch.utils.data.DataLoader(
        dataset=mnist_dataset,
        batch_size=100,
        shuffle=True)

    return mnist_data_loader

In [229]:
mnist_data_loader = get_mnist()

In [236]:
len(mnist_data_loader)

600

In [269]:
for step,(x,y) in enumerate(mnist_data_loader):
    print('第{}个样本的图片大小为{}，标签大小为{}'.format(step + 1, x.shape, y.shape))
    print(x.shape)
    print(y.shape)
    
    if step == 1:
        break

第1个样本的图片大小为torch.Size([100, 1, 28, 28])，标签大小为torch.Size([100])
torch.Size([100, 1, 28, 28])
tensor([2, 2, 1, 8, 2, 2, 1, 8, 6, 2, 5, 3, 4, 1, 0, 8, 6, 7, 7, 8, 3, 4, 8, 9,
        5, 1, 0, 9, 0, 5, 5, 1, 9, 1, 8, 9, 9, 4, 7, 8, 3, 6, 4, 8, 2, 8, 4, 3,
        1, 5, 4, 7, 7, 1, 4, 2, 0, 2, 2, 7, 7, 8, 5, 1, 5, 2, 4, 5, 6, 1, 5, 2,
        4, 2, 0, 4, 6, 9, 6, 1, 6, 0, 2, 2, 9, 6, 0, 9, 6, 6, 4, 2, 1, 3, 3, 8,
        6, 2, 9, 1])
第2个样本的图片大小为torch.Size([100, 1, 28, 28])，标签大小为torch.Size([100])
torch.Size([100, 1, 28, 28])
tensor([6, 9, 9, 3, 6, 5, 9, 2, 7, 3, 0, 6, 3, 4, 2, 9, 7, 3, 0, 7, 3, 4, 4, 2,
        1, 5, 0, 3, 1, 9, 0, 9, 6, 1, 1, 0, 2, 8, 7, 9, 4, 8, 3, 1, 9, 1, 8, 0,
        8, 6, 6, 1, 4, 0, 0, 0, 3, 0, 5, 4, 7, 6, 9, 8, 0, 9, 8, 4, 1, 5, 1, 9,
        9, 1, 4, 8, 1, 5, 1, 2, 1, 5, 7, 1, 0, 0, 4, 6, 8, 7, 5, 4, 6, 7, 0, 6,
        4, 7, 2, 9])


In [ ]:
class LeNetEncoder(nn.Module):
    """LeNet encoder model for ADDA."""

    def __init__(self):
        """Init LeNet encoder."""
        super(LeNetEncoder, self).__init__()

        self.restored = False

        self.encoder = nn.Sequential(
            # 1st conv layer
            # input [1 x 28 x 28]
            # output [20 x 12 x 12]

            #my input[1*1*n]
            #my output[20*1/2*n/2]

            nn.Conv2d(1, 20, kernel_size=5),
            nn.MaxPool2d(kernel_size=2),
            nn.ReLU(),
            # 2nd conv layer
            # input [20 x 12 x 12]
            # output [50 x 4 x 4]

            nn.Conv2d(20, 50, kernel_size=5),
            nn.Dropout2d(),
            nn.MaxPool2d(kernel_size=2),
            nn.ReLU()
        )
            #经过全连接层（即分类层）转换后，encoder编码输出大小为500(500是人为设定的)
        self.fc1 = nn.Linear(50 * 4 * 4, 500)


    def forward(self, input):
        """Forward the LeNet."""
        conv_out = self.encoder(input)
        feat = self.fc1(conv_out.view(-1, 50 * 4 * 4))  #经过卷积层后，先把conv_out变成（n行，50*4*4列），再输入全链接层
        return feat

In [ ]:
class LeNetEncoder(nn.Module):
    def __init__(self):
        super(LeNetEncoder,self).__init__()
        self.restored = False
        self.encoder = nn.Sequential(
            #第一层1维卷积，卷积核尺寸为3*3，步长为1
            nn.Conv1d(1,20,kernal_size=3),
            #池化层，卷积核尺寸为2*2，步长为2（1可否？）
            nn.MaxPool1d(kernal_size=2,stride=2)
            nn.ReLu(),
            #第二层1维卷积，同上
            nn.Conv1d(20,50,kernal_size=3),
            nn.Dropout(),
            nn.MaxPool1d(kernal_size=2,stride=2)
            nn.ReLu()
        )
        self.fc1 = nn.Linear(50 * 1, 40)
        
    def put_forward(self,input):
        conv_out = self.encoder(input)
        feat = self.fc1(conv_out.view(-1, 50 * 1))
        return feat

In [217]:
"""Pre-train encoder and classifier for source dataset."""

import torch.nn as nn
import torch.optim as optim

import params
from utils import make_variable, save_model

#对于源域进行空间映射和分类器训练
def train_src(encoder, classifier, data_loader):
    """Train classifier for source domain."""
    ####################
    # 1. setup network #
    ####################

    # set train state for Dropout and BN layers
    encoder.train()
    classifier.train()

    # setup criterion and optimizer
    optimizer = optim.Adam(
        list(encoder.parameters()) + list(classifier.parameters()),  #可能不能一起训练
        lr=params.c_learning_rate,
        betas=(params.beta1, params.beta2))
    # criterion = nn.CrossEntropyLoss()
    #my
    criterion = nn.MSELoss()

    ####################
    # 2. train network #
    ####################

    for epoch in range(params.num_epochs_pre):    #100
        for step, (images, labels) in enumerate(data_loader):
            # make images and labels variable 将图片变成数据
            images = make_variable(images)
            labels = make_variable(labels.squeeze_())

            # zero gradients for optimizer
            optimizer.zero_grad()

            # compute loss for critic
            preds = classifier(encoder(images))
            loss = criterion(preds, labels)

            # optimize source classifier
            loss.backward()
            optimizer.step()

            # print step info
            if ((step + 1) % params.log_step_pre == 0):
                print("Epoch [{}/{}] Step [{}/{}]: loss={}"
                      .format(epoch + 1,
                              params.num_epochs_pre,
                              step + 1,
                              len(data_loader),
                              loss.data[0]))

        # eval model on test set
        if ((epoch + 1) % params.eval_step_pre == 0):
            eval_src(encoder, classifier, data_loader)

        # save model parameters
#         if ((epoch + 1) % params.save_step_pre == 0):
#             save_model(encoder, "ADDA-source-encoder-{}.pt".format(epoch + 1))
#             save_model(
#                 classifier, "ADDA-source-classifier-{}.pt".format(epoch + 1))

#     # # save final model
#     save_model(encoder, "ADDA-source-encoder-final.pt")
#     save_model(classifier, "ADDA-source-classifier-final.pt")

    return encoder, classifier


def eval_src(encoder, classifier, data_loader):
    """Evaluate classifier for source domain."""
    # set eval state for Dropout and BN layers
    encoder.eval()
    classifier.eval()

    # init loss and accuracy
    loss = 0
    acc = 0

    # set loss function
    # criterion = nn.CrossEntropyLoss()

    #my
    criterion = nn.MSELoss()

    # evaluate network
    for (images, labels) in data_loader:
        images = make_variable(images, volatile=True)
        labels = make_variable(labels)

        preds = classifier(encoder(images))
        loss += criterion(preds, labels).item()  #data[0]6

        # pred_cls = preds.data.max(1)[1] #返回每一行最大值所在的索引(我的不需要，因为分类器（即我的回归器)直接输出一个结果)
        # acc += pred_cls.eq(labels.data).cpu().sum()
        acc += (preds - labels) ** 2

    loss /= len(data_loader)
    acc /= len(data_loader.dataset)

    print("Avg Loss = {}, Avg Accuracy = {:2%}".format(loss, acc))


In [218]:
"""LeNet model for ADDA."""

import torch.nn.functional as F
from torch import nn


#编码器：映射到相同空间

#我的编码器
class LeNetEncoder(nn.Module):
    def __init__(self):
        super(LeNetEncoder, self).__init__()
        self.restored = False
        self.encoder = nn.Sequential(
            # 第一层1维卷积，卷积核尺寸为3*3，步长为1
            nn.Conv1d(1, 20, kernel_size=3),
            # 池化层，卷积核尺寸为2*2，步长为2（1可否？）
            nn.MaxPool1d(kernel_size=2, stride=2),
            nn.ReLU(),
            # 第二层1维卷积，同上
            nn.Conv1d(20, 50, kernel_size=3),
            nn.Dropout(),
            nn.MaxPool1d(kernel_size=2, stride=2),
            nn.ReLU()
            )
        self.fc1 = nn.Linear(50 * 1, 40)

    def forward(self, input):
        conv_out = self.encoder(input)
        feat = self.fc1(conv_out.view(-1, 50 * 1))
        return feat


#我的回归器
class LeNetRegressor(nn.Module):
    """LeNet classifier model for ADDA."""
    def __init__(self):
        super(LeNetRegressor, self).__init__()
        self.fc2 = nn.Linear(40,1)   #输出格式大小为1

    def forward(self, feat):
        out = F.dropout(F.relu(feat), training=self.training)
        out = self.fc2(out)
        return out

In [222]:
def get_data_loader():
    source_x = torch.from_numpy(np.array(
        (pd.read_csv(r'D:/个人资料/研究生/机器学习/Jupyter/迁移学习练习赛-2/run/data/source_x.csv').iloc[:, 1:]).astype('float32')))
    source_y = torch.from_numpy(np.array(
        (pd.read_csv(r'D:/个人资料/研究生/机器学习/Jupyter/迁移学习练习赛-2/run/data/source_y.csv').iloc[:, 1:]).astype('float32')))
    target_x = torch.from_numpy(np.array(
        (pd.read_csv(r'D:/个人资料/研究生/机器学习/Jupyter/迁移学习练习赛-2/run/data/target_x.csv').iloc[:, 1:]).astype('float32')))
    target_y = torch.from_numpy(np.array(
        (pd.read_csv(r'D:/个人资料/研究生/机器学习/Jupyter/迁移学习练习赛-2/run/data/target_y.csv').iloc[:, 1:]).astype('float32')))
    # test = pd.read_csv(r'data/test.csv')
    #扩大数据维度，原来的【314*9】转变为【314*1*1*9】

    # source_x = torch.unsqueeze(source_x, 1)
    source_x = torch.unsqueeze(source_x, 1)
    # target_x = torch.unsqueeze(target_x, 1)
    target_x = torch.unsqueeze(target_x, 1)

    #运用批训练
    source_data = Data.TensorDataset(source_x, source_y)
    target_data = Data.TensorDataset(target_x, target_y)

    source_data_loader = Data.DataLoader(
        dataset=source_data,
        batch_size=params.batch_size,
        shuffle=True
    )
    target_data_loader = Data.DataLoader(
        dataset=target_data,
        batch_size=params.batch_size,
        shuffle=True
    )
    return (source_data_loader,target_data_loader)

In [223]:
my_regressor = LeNetRegressor()
my_encoder = LeNetEncoder()
src_data_loader, tgt_data_loader = get_data_loader()
src_data_loader_eval, tgt_data_loader_eval = get_data_loader()

In [ ]:
train_src()

In [288]:
def get_data_loader():
    source_x = torch.from_numpy(np.array(
        (pd.read_csv(r'D:/个人资料/研究生/机器学习/Jupyter/迁移学习练习赛-2/run/data/source_x.csv').iloc[:, 1:]).astype('float32')))
    source_y = torch.from_numpy(np.array(
        (pd.read_csv(r'D:/个人资料/研究生/机器学习/Jupyter/迁移学习练习赛-2/run/data/source_y.csv').iloc[:, 1:]).astype('float32')))
    target_x = torch.from_numpy(np.array(
        (pd.read_csv(r'D:/个人资料/研究生/机器学习/Jupyter/迁移学习练习赛-2/run/data/target_x.csv').iloc[:, 1:]).astype('float32')))
    target_y = torch.from_numpy(np.array(
        (pd.read_csv(r'D:/个人资料/研究生/机器学习/Jupyter/迁移学习练习赛-2/run/data/target_y.csv').iloc[:, 1:]).astype('float32')))
    # test = pd.read_csv(r'data/test.csv')
    #扩大数据维度，原来的【314*9】转变为【314*1*1*9】

    #x扩充至三维
    # source_x = torch.unsqueeze(source_x, 1)
    source_x = torch.unsqueeze(source_x, 1)
    # target_x = torch.unsqueeze(target_x, 1)
    target_x = torch.unsqueeze(target_x, 1)
    #y减少至一维
#     source_y = torch.squeeze(source_y, 1)
#     target_y = torch.squeeze(target_y, 1)

    #运用批训练
    source_data = Data.TensorDataset(source_x, source_y)
    target_data = Data.TensorDataset(target_x, target_y)

    source_data_loader = Data.DataLoader(
        dataset=source_data,
        batch_size=params.batch_size,
        shuffle=True
    )
    target_data_loader = Data.DataLoader(
        dataset=target_data,
        batch_size=params.batch_size,
        shuffle=True
    )
    return (source_data_loader,target_data_loader)


In [295]:
target_x.shape

torch.Size([78, 1, 1, 9])

In [289]:
src_data_loader, tgt_data_loader = get_data_loader()

In [290]:
for i in src_data_loader:
    print(i)

[tensor([[[-0.8693, -1.0190, -0.8890, -1.1853, -0.2364,  0.5718, -1.2868,
           2.1430, -0.4952]],

        [[ 0.3073,  0.3516, -0.1278, -0.2385, -0.2005, -0.7885,  0.7747,
          -0.4651, -0.4952]],

        [[-0.8693, -0.9424, -0.7053, -0.8179, -0.3798, -0.5164, -1.2868,
           2.1430, -0.4952]],

        [[ 1.4839,  1.9618,  1.6309,  2.2701, -1.0968, -0.7885,  0.7747,
          -0.4651, -0.4952]],

        [[ 1.4839,  1.0225,  0.9222,  1.9525,  0.1580, -0.5164,  0.7747,
          -0.4651, -0.4952]],

        [[-0.8693, -0.7027, -0.4953, -0.9127, -0.5590, -1.3326,  0.7747,
          -0.4651, -0.4952]],

        [[-0.8693, -1.0766, -1.1515, -1.1699,  1.2336, -0.5164, -1.2868,
          -0.4651,  2.0129]],

        [[-0.8693, -0.9424, -1.3353, -0.8724,  2.8469, -1.0605, -1.2868,
           2.1430, -0.4952]],

        [[-0.8693, -0.5302, -0.4953, -0.2373,  0.0146,  1.6601,  0.7747,
          -0.4651, -0.4952]],

        [[-0.8693, -0.9424, -0.4428, -1.0194, -0.3798, -1.6046,

In [291]:
acc = 0
for step, (x, y) in enumerate(src_data_loader):
    print(x.shape,y.shape)
    preds = my_regressor(my_encoder(x)) #.squeeze()
    print(y)
    print(preds)
    acc += ((preds - y) ** 2).cpu().sum()
    print(acc)

torch.Size([50, 1, 9]) torch.Size([50, 1])
tensor([[23.2000],
        [25.5000],
        [32.3000],
        [30.5000],
        [14.0000],
        [37.0000],
        [25.4000],
        [33.0000],
        [13.0000],
        [22.3000],
        [23.0000],
        [15.5000],
        [36.0000],
        [26.0000],
        [30.0000],
        [18.0000],
        [34.3000],
        [19.2000],
        [20.2000],
        [15.0000],
        [15.0000],
        [16.0000],
        [32.2000],
        [20.2000],
        [27.0000],
        [16.0000],
        [20.0000],
        [37.7000],
        [13.0000],
        [28.8000],
        [20.0000],
        [27.0000],
        [14.0000],
        [23.0000],
        [22.0000],
        [16.2000],
        [12.0000],
        [23.0000],
        [17.0000],
        [15.0000],
        [13.0000],
        [20.0000],
        [36.0000],
        [17.0000],
        [31.0000],
        [25.0000],
        [20.6000],
        [11.0000],
        [18.0000],
        [21.0000]])
tensor

In [292]:
acc2 = acc.detach().numpy()

In [293]:
acc2

array(189760.47, dtype=float32)

In [294]:
acc/314

tensor(604.3327, grad_fn=<DivBackward0>)

In [318]:
a = torch.FloatTensor(3,1)
b = torch.FloatTensor(3,1)

In [337]:
print(a)
print(b)
c = a-b
print(((a-b)))
print(c**2)
print((c**2).cpu().sum())

tensor([[-1.2961e+17],
        [ 4.5912e-41],
        [ 0.0000e+00]])
tensor([[4.2039e-45],
        [0.0000e+00],
        [1.4013e-45]])
tensor([[-1.2961e+17],
        [ 4.5912e-41],
        [-1.4013e-45]])
tensor([[1.6797e+34],
        [0.0000e+00],
        [0.0000e+00]])
tensor(1.6797e+34)


In [327]:
c = ((a-b)**2).cpu().sum()
c

tensor(1.6797e+34)

In [321]:
c

tensor([[1.6797e+34],
        [0.0000e+00],
        [0.0000e+00]])

In [329]:
(a.numpy()-b.numpy())**2

array([[1.6797475e+34],
       [0.0000000e+00],
       [0.0000000e+00]], dtype=float32)

In [331]:
5.5**2+4.6**2+1.4**2

53.37